# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- 
  binary: wms
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - 386
  - amd64
  main: ./cli
  env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
    - "wroge/wms:latest"
    - "wroge/wms:{{ .Tag }}"
scoop:
  # Repository to push the app manifest to.
  bucket:
    owner: wroge
    name: scoop-bucket
  commit_author:
    name: wroge
  homepage: https://github.com/wroge/wms
  description: "Extension for easy use of Web Map Services."
brew:
    github:
      owner: wroge
      name: homebrew-tap
    description: "Extension for easy use of Web Map Services."
    homepage:  https://github.com/wroge/wms
    folder: Formula